language: objective-c

before_install:
  - brew update
  - brew unlink xctool
  - brew install xctool

script:
  - xctool clean build test -project CITest.xcodeproj -scheme CITest -sdk iphonesimulator7.1 ONLY_ACTIVE_ARCH=NO
