language: objective-c

before_install:
  - brew update
  - brew upgrade xctool

script:
  - xctool -project CITest.xcodeproj -scheme CITest -sdk iphonesimulator7.1 ONLY_ACTIVE_ARCH=NO
  - xctool test -project CITest.xcodeproj -scheme CITest -sdk iphonesimulator7.1 ONLY_ACTIVE_ARCH=NO
