language: objective-c

env:
  global:
    - APPNAME="CITest"
    - 'DEVELOPER_NAME="iPhone Distribution: EL Passion Next Sp. z o.o."'
    - PROFILE_UUID=F3EDBAED-2997-40C9-87CC-EF3B70C99BB5
    - secure: VEgrIu1zTxcEOCBjES43Cw2UDL5dHYfdjE8zhantimYlyIu/9MlUQUt74ZgzI1hylejcjIQh0az9A1AX4UXWC5HAyYRLmUp4emAy6dfLNmk+dOStgBm8M186Jo+SjhyN4TrHFgragRIksJYvVu2dGkxgSX48QaNULnycB+Vs4z8=
    - secure: RkQK6YQ6B1hBHthivNaqANDGxsj2/Xl0K+gv+seaNaJ2sS3TBTn4aWUAypVz3x4oZVMa50LtFOFzfTCeNLdDS/DzFxqrXPK8jw/p3hes8o3hSQKEhaoW4uapZRnZUdL+5x6X7dnhl+GZ2bPkbSAiK2LXvfOXS0dKC0+RD/aocV4=

before_install:
  - brew update
  - brew unlink xctool
  - brew install xctool
  - gem install cocoapods

before_script:
  - export LANG=en_US.UTF-8

script:
  - xctool clean build test -workspace CITest.xcworkspace -scheme CITest -sdk iphonesimulator7.1 ONLY_ACTIVE_ARCH=NO
