language: objective-c

before_install:
  - brew update
  - brew unlink xctool
  - brew install xctool
  - gem install cocoapods

before_script:
  - export LANG=en_US.UTF-8

script:
  - xctool clean build test -workspace CITest.xcworkspace -scheme CITest -sdk iphonesimulator7.1 ONLY_ACTIVE_ARCH=NO
