language: objective-c

env:
  global:
    secure: VEgrIu1zTxcEOCBjES43Cw2UDL5dHYfdjE8zhantimYlyIu/9MlUQUt74ZgzI1hylejcjIQh0az9A1AX4UXWC5HAyYRLmUp4emAy6dfLNmk+dOStgBm8M186Jo+SjhyN4TrHFgragRIksJYvVu2dGkxgSX48QaNULnycB+Vs4z8=

before_install:
  - brew update
  - brew unlink xctool
  - brew install xctool
  - gem install cocoapods

before_script:
  - export LANG=en_US.UTF-8

script:
  - xctool clean build test -workspace CITest.xcworkspace -scheme CITest -sdk iphonesimulator7.1 ONLY_ACTIVE_ARCH=NO
